/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_DATASEALING_ARGS_H
#define EDGER8R_DATASEALING_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
#include "common/shared.h"

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _seal_data_args_t
{
    oe_result_t _result;
    int _retval;
    int sealPolicy;
    unsigned char* opt_mgs;
    size_t opt_msg_len;
    unsigned char* data;
    size_t data_size;
    sealed_data_t** sealed_data;
    size_t* sealed_data_size;
} seal_data_args_t;

typedef struct _unseal_data_args_t
{
    oe_result_t _result;
    int _retval;
    sealed_data_t* sealed_data;
    size_t sealed_data_size;
    unsigned char** data;
    size_t* data_size;
} unseal_data_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    datasealing_fcn_id_seal_data = 0,
    datasealing_fcn_id_unseal_data = 1,
    datasealing_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    datasealing_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_DATASEALING_ARGS_H
