pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd openenclave
      echo "cd openenclave"
            
      echo "sudo scripts/ansible/install-ansible.sh"
      sudo scripts/ansible/install-ansible.sh
            
      echo "sudo ansible-playbook scripts/ansible/oe-contributors-setup.yml"
      sudo ansible-playbook scripts/ansible/oe-contributors-setup.yml
            
      echo "mkdir build"
      mkdir build
            
      echo "cd build"
      cd build
            
      echo "cmake -G"
      cmake -G "Ninja" ..
            
      echo "ninja"
      ninja
