# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.
pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |

      echo $(linux-sas)
      echo "sudo scripts/ansible/install-ansible.sh"
      sudo scripts/ansible/install-ansible.sh

      echo "sudo ansible-playbook scripts/ansible/oe-contributors-setup.yml"
      sudo ansible-playbook scripts/ansible/oe-contributors-setup.yml

      echo "mkdir build"
      mkdir build

      echo "cd build"
      cd build

      echo "cmake -DHAS_QUOTE_PROVIDER=OFF .."
      cmake -DHAS_QUOTE_PROVIDER=OFF ..

      echo "make"
      make

      echo "sudo make install"
      sudo make install

      echo "build OE samples"

      cd ..
      echo "Source openenclaverc"
      . build/output/share/openenclave/openenclaverc

      echo "find samples"
      find samples  -name Makefile -execdir make \;

      echo "create fuzz test folders"
      mkdir ~/fuzzUpload-bins
      mkdir ~/fuzzUpload-seeds
      mkdir ~/fuzzUpload-bins/oesigndump ~/fuzzUpload-bins/oesignsign ~/fuzzUpload-bins/oeedger8r ~/fuzzUpload-bins/tcbinfo_test  ~/fuzzUpload-bins/sgxextensions_test ~/fuzzUpload-bins/qeidentity_test 
      mkdir ~/fuzzUpload-seeds/oesigndump ~/fuzzUpload-seeds/oesigndump/seeds ~/fuzzUpload-seeds/oesignsign ~/fuzzUpload-seeds/oesignsign/seeds ~/fuzzUpload-seeds/oeedger8r ~/fuzzUpload-seeds/oeedger8r/seeds ~/fuzzUpload-seeds/tcbinfo_test ~/fuzzUpload-seeds/tcbinfo_test/seeds ~/fuzzUpload-seeds/sgxextensions_test ~/fuzzUpload-seeds/sgxextensions_test/seeds ~/fuzzUpload-seeds/qeidentity_test ~/fuzzUpload-seeds/qeidentity_test/seeds

      echo "copy test collaterals for oeedger8r"
      sudo cp build/tools/oeedger8r/_build/install/default/bin/oeedger8r ~/fuzzUpload-bins/oeedger8r/
      sudo cp `find samples -name *.edl` ~/fuzzUpload-seeds/oeedger8r/seeds

      echo "copy test collaterals for oesign dump"
      sudo cp build/output/bin/oesign ~/fuzzUpload-bins/oesigndump/oesigndump
      sudo cp `find samples -name *.signed` ~/fuzzUpload-seeds/oesigndump/seeds

      echo "copy test collaterals for oesign sign"
      sudo cp build/output/bin/oesign ~/fuzzUpload-bins/oesignsign/oesignsign
      sudo cp `find samples -name *.signed | cut -f -1 -d.` ~/fuzzUpload-seeds/oesignsign/seeds
      sudo cp `find samples -name enc.conf` ~/fuzzUpload-seeds/oesignsign/
      sudo cp `find samples -name private.pem` ~/fuzzUpload-seeds/oesignsign/

      echo "copy test collaterals for tcbinfo parser"
      sudo cp build/tests/fuzztests/tcbinfo_test ~/fuzzUpload-bins/tcbinfo_test
      sudo cp build/tests/fuzztests/seeds/tcbinfoparser/* ~/fuzzUpload-seeds/tcbinfo_test/seeds

      echo "copy test collaterals for sgx extension parser"
      sudo cp build/tests/fuzztests/sgxextensions_test ~/fuzzUpload-bins/sgxextensions_test
      sudo cp build/tests/fuzztests/seeds/parcesgxextensions/* ~/fuzzUpload-seeds/sgxextensions_test/seeds

      echo "copy test collaterals for qe identity parser"
      sudo cp build/tests/fuzztests/qeidentity_test ~/fuzzUpload-bins/qeidentity_test
      sudo cp build/tests/fuzztests/seeds/qeidentity/* ~/fuzzUpload-seeds/qeidentity_test/seeds

      echo "rename seeds for oesign with same extensions (demanded by fuzzer)"
      cd ~/fuzzUpload-seeds/oesignsign/seeds
      for f in *;do sudo mv $f $f.unsigned;done

      cd ~/
      sudo chmod -R 777 ~/fuzzUpload-bins
      zip -r linux-bins.zip ~/fuzzUpload-bins

      cd ~/
      sudo chmod -R 777 ~/fuzzUpload-seeds
      zip -r linux-seeds.zip ~/fuzzUpload-seeds
      
      #Download AzCopy
      wget https://aka.ms/downloadazcopy-v10-linux
      
      #Expand Archive
      tar -xvf downloadazcopy-v10-linux
      
      #(Optional) Remove existing AzCopy version
      sudo rm /usr/bin/azcopy
      
      #Move AzCopy to the destination you want to store it
      sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/

      azcopy copy 'linux-bins.zip' 'https://fuzztestingstorage.blob.core.windows.net/linux/$(linux-sas)'
      azcopy copy 'linux-seeds.zip' 'https://fuzztestingstorage.blob.core.windows.net/linux/$(linux-sas)'