  0.9PSWUpdate[m
  2016_2019[m
  DocUpdates[m
  MoreBadges[m
  PermLinks[m
  addIntelDeps[m
  addMissingTest[m
  brmclare/#2727[m
  brmclare/2716[m
  brmclare/2727[m
  ciBadge[m
  ctestFix[m
  disable2019FromPR[m
  disable2019Test[m
* [32me2eLite[m
  extendBorstimeout[m
  fixNightlyBuilds[m
  fixNightlyBuils[m
  fixNightlyTestingBadge[m
  lowerBorsTimeout[m
  master[m
  removeRedundantBadge[m
  revertLine505[m
  revertLine653[m
  rhelTestingExpansion[m
  stressTest[m
  stressTest2[m
  updateIntelPSW[m
  updateIntelPSW1[m
  updatePSW[m
  v0.9.x[m
  windowsBandaid[m
  windowsUpdates[m
