/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_REMOTEATTESTATION_T_H
#define EDGER8R_REMOTEATTESTATION_T_H

#include <openenclave/enclave.h>

#include "remoteattestation_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int get_remote_report_with_pubkey(
    uint8_t** pem_key,
    size_t* key_size,
    uint8_t** remote_report,
    size_t* remote_report_size);

int verify_report_and_set_pubkey(
    uint8_t* pem_key,
    size_t key_size,
    uint8_t* remote_report,
    size_t remote_report_size);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_REMOTEATTESTATION_T_H
