/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_T_H
#define EDGER8R_SWITCHLESS_T_H

#include <openenclave/enclave.h>

#include "switchless_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
void enclave_add_N_switchless(
    int* m,
    int n);

void enclave_add_N_regular(
    int* m,
    int n);

/**** OCALL prototypes. ****/
oe_result_t host_increment_switchless(int* m);

oe_result_t host_increment_regular(int* m);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_T_H
