/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_FILEENCRYPTOR_U_H
#define EDGER8R_FILEENCRYPTOR_U_H

#include <openenclave/host.h>

#include "fileencryptor_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_fileencryptor_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t initialize_encryptor(
    oe_enclave_t* enclave,
    int* _retval,
    bool encrypt,
    const char* password,
    size_t password_len,
    encryption_header_t* header);

oe_result_t encrypt_block(
    oe_enclave_t* enclave,
    int* _retval,
    bool encrypt,
    unsigned char* input_buf,
    unsigned char* output_buf,
    size_t size);

oe_result_t close_encryptor(oe_enclave_t* enclave);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_FILEENCRYPTOR_U_H
