/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "fileencryptor_t.h"

#include <openenclave/edger8r/enclave.h>

#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/**** ECALL functions. ****/

void ecall_initialize_encryptor(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    initialize_encryptor_args_t* pargs_in = (initialize_encryptor_args_t*)input_buffer;
    initialize_encryptor_args_t* pargs_out = (initialize_encryptor_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->password)
        OE_SET_IN_POINTER(password, (pargs_in->password_len * sizeof(char)), char*);
    if (pargs_in->header)
        OE_SET_IN_OUT_POINTER(header, sizeof(encryption_header_t), encryption_header_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->header)
        OE_COPY_AND_SET_IN_OUT_POINTER(header, sizeof(encryption_header_t), encryption_header_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = initialize_encryptor(
        pargs_in->encrypt,
        (const char*)pargs_in->password,
        pargs_in->password_len,
        pargs_in->header);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_encrypt_block(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    encrypt_block_args_t* pargs_in = (encrypt_block_args_t*)input_buffer;
    encrypt_block_args_t* pargs_out = (encrypt_block_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->input_buf)
        OE_SET_IN_POINTER(input_buf, (pargs_in->size * sizeof(unsigned char)), unsigned char*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->output_buf)
        OE_SET_OUT_POINTER(output_buf, (pargs_in->size * sizeof(unsigned char)), unsigned char*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = encrypt_block(
        pargs_in->encrypt,
        pargs_in->input_buf,
        pargs_in->output_buf,
        pargs_in->size);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_close_encryptor(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    close_encryptor_args_t* pargs_in = (close_encryptor_args_t*)input_buffer;
    close_encryptor_args_t* pargs_out = (close_encryptor_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    close_encryptor(
    );

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

/**** ECALL function table. ****/

oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_initialize_encryptor,
    (oe_ecall_func_t) ecall_encrypt_block,
    (oe_ecall_func_t) ecall_close_encryptor
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

/**** OCALL function wrappers. ****/

/* There were no ocalls. */
OE_EXTERNC_END
