/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_FILEENCRYPTOR_T_H
#define EDGER8R_FILEENCRYPTOR_T_H

#include <openenclave/enclave.h>

#include "fileencryptor_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int initialize_encryptor(
    bool encrypt,
    const char* password,
    size_t password_len,
    encryption_header_t* header);

int encrypt_block(
    bool encrypt,
    unsigned char* input_buf,
    unsigned char* output_buf,
    size_t size);

void close_encryptor(void);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_FILEENCRYPTOR_T_H
