/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_LOCALATTESTATION_T_H
#define EDGER8R_LOCALATTESTATION_T_H

#include <openenclave/enclave.h>

#include "localattestation_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int get_target_info(
    uint8_t** target_info_buffer,
    size_t* target_info_size);

int get_targeted_report_with_pubkey(
    uint8_t* target_info_buffer,
    size_t target_info_size,
    uint8_t** pem_key,
    size_t* pem_key_size,
    uint8_t** report,
    size_t* report_size);

int verify_report_and_set_pubkey(
    uint8_t* pem_key,
    size_t key_size,
    uint8_t* report,
    size_t report_size);

int generate_encrypted_message(
    uint8_t** data,
    size_t* size);

int process_encrypted_msg(
    uint8_t* data,
    size_t size);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_LOCALATTESTATION_T_H
