/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_TLS_CLIENT_U_H
#define EDGER8R_TLS_CLIENT_U_H

#include <openenclave/host.h>

#include "tls_client_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_tls_client_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t launch_tls_client(
    oe_enclave_t* enclave,
    int* _retval,
    char* server_name,
    char* server_port);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_TLS_CLIENT_U_H
