/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_U_H
#define EDGER8R_SWITCHLESS_U_H

#include <openenclave/host.h>

#include "switchless_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_switchless_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t enclave_add_N_switchless(
    oe_enclave_t* enclave,
    int* m,
    int n);

oe_result_t enclave_add_N_regular(
    oe_enclave_t* enclave,
    int* m,
    int n);

/**** OCALL prototypes. ****/
void host_increment_switchless(int* m);

void host_increment_regular(int* m);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_U_H
