/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_DATASEALING_T_H
#define EDGER8R_DATASEALING_T_H

#include <openenclave/enclave.h>

#include "datasealing_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int seal_data(
    int sealPolicy,
    unsigned char* opt_mgs,
    size_t opt_msg_len,
    unsigned char* data,
    size_t data_size,
    sealed_data_t** sealed_data,
    size_t* sealed_data_size);

int unseal_data(
    sealed_data_t* sealed_data,
    size_t sealed_data_size,
    unsigned char** data,
    size_t* data_size);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_DATASEALING_T_H
