/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "datasealing_t.h"

#include <openenclave/edger8r/enclave.h>

#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/**** ECALL functions. ****/

void ecall_seal_data(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    seal_data_args_t* pargs_in = (seal_data_args_t*)input_buffer;
    seal_data_args_t* pargs_out = (seal_data_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->opt_mgs)
        OE_SET_IN_POINTER(opt_mgs, pargs_in->opt_msg_len, unsigned char*);
    if (pargs_in->data)
        OE_SET_IN_POINTER(data, pargs_in->data_size, unsigned char*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->sealed_data)
        OE_SET_OUT_POINTER(sealed_data, sizeof(sealed_data_t*), sealed_data_t**);
    if (pargs_in->sealed_data_size)
        OE_SET_OUT_POINTER(sealed_data_size, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = seal_data(
        pargs_in->sealPolicy,
        pargs_in->opt_mgs,
        pargs_in->opt_msg_len,
        pargs_in->data,
        pargs_in->data_size,
        pargs_in->sealed_data,
        pargs_in->sealed_data_size);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

void ecall_unseal_data(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    unseal_data_args_t* pargs_in = (unseal_data_args_t*)input_buffer;
    unseal_data_args_t* pargs_out = (unseal_data_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->sealed_data)
        OE_SET_IN_POINTER(sealed_data, pargs_in->sealed_data_size, sealed_data_t*);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->data)
        OE_SET_OUT_POINTER(data, sizeof(unsigned char*), unsigned char**);
    if (pargs_in->data_size)
        OE_SET_OUT_POINTER(data_size, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = unseal_data(
        pargs_in->sealed_data,
        pargs_in->sealed_data_size,
        pargs_in->data,
        pargs_in->data_size);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out))
        pargs_out->_result = _result;
}

/**** ECALL function table. ****/

oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_seal_data,
    (oe_ecall_func_t) ecall_unseal_data
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

/**** OCALL function wrappers. ****/

/* There were no ocalls. */
OE_EXTERNC_END
