/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_LOCALATTESTATION_ARGS_H
#define EDGER8R_LOCALATTESTATION_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _get_target_info_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t** target_info_buffer;
    size_t* target_info_size;
} get_target_info_args_t;

typedef struct _get_targeted_report_with_pubkey_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t* target_info_buffer;
    size_t target_info_size;
    uint8_t** pem_key;
    size_t* pem_key_size;
    uint8_t** report;
    size_t* report_size;
} get_targeted_report_with_pubkey_args_t;

typedef struct _verify_report_and_set_pubkey_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t* pem_key;
    size_t key_size;
    uint8_t* report;
    size_t report_size;
} verify_report_and_set_pubkey_args_t;

typedef struct _generate_encrypted_message_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t** data;
    size_t* size;
} generate_encrypted_message_args_t;

typedef struct _process_encrypted_msg_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t* data;
    size_t size;
} process_encrypted_msg_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    localattestation_fcn_id_get_target_info = 0,
    localattestation_fcn_id_get_targeted_report_with_pubkey = 1,
    localattestation_fcn_id_verify_report_and_set_pubkey = 2,
    localattestation_fcn_id_generate_encrypted_message = 3,
    localattestation_fcn_id_process_encrypted_msg = 4,
    localattestation_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    localattestation_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_LOCALATTESTATION_ARGS_H
